# Generated by Django 4.2.4 on 2023-09-01 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=255, verbose_name='улица')),
                ('building_number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('model', models.CharField(max_length=255, verbose_name='модель')),
                ('release_date', models.DateField(verbose_name='дата выхода продукта на рынок')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='название')),
                ('supplier', models.SmallIntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], default=2, verbose_name='поставщик')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='задолженность')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Время создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.contacts', verbose_name='контакты')),
                ('product', models.ManyToManyField(to='supplier.product', verbose_name='продукт')),
            ],
        ),
    ]
