# Generated by Django 4.2.4 on 2023-09-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Участник сети', 'verbose_name_plural': 'Участники сети'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='country',
            field=models.CharField(max_length=100, verbose_name='страна'),
        ),
    ]
